const Tag = require("../models/Tag");
const Category = require("../models/Category");
const { sanitizeContent, sanitizeInline, toPlainText } = require("../utils/sanitizeContent");
const { escapeRegex } = require("../utils/escapeHtml");
const {
  makeSlug,
  normalizeImage,
  normalizeGallery,
  calcReadTime,
  makeExcerpt,
  parseList,
  parseDate,
  parseNumber,
  toBool,
} = require("../utils/newsHelpers");

/* =========================================================
   TAGS
========================================================= */

/**
 * Resolve tag input to Tag ids. Accepts ["6501..","6502.."] | ["Bali","Visa"] | "Bali, Visa".
 * With `create: false` unknown names are ignored instead of being created.
 * @returns {Promise<{ids: string[], names: string[]}>}
 */
const resolveTags = async (input, { create = true } = {}) => {
  const raw = parseList(input);
  const ids = [];
  const names = [];

  for (const entry of raw) {
    const value = String(entry).trim();
    if (!value) continue;

    if (/^[0-9a-fA-F]{24}$/.test(value)) {
      const existing = await Tag.findById(value).select("name").lean();
      if (existing) {
        ids.push(existing._id);
        names.push(existing.name);
        continue;
      }
    }

    const slug = makeSlug(value);
    if (!slug) continue;

    const tag = create ? await findOrCreateTag(slug, value) : await Tag.findOne({ slug }).select("name").lean();
    if (!tag) continue;

    ids.push(tag._id);
    names.push(tag.name);
  }

  return { ids, names };
};

/**
 * Get a tag by slug, creating it if it is new. Imports process rows
 * concurrently, so an atomic upsert handles races; the retry covers the narrow
 * window where two upserts still collide on the unique index.
 */
const findOrCreateTag = async (slug, name) => {
  try {
    return await Tag.findOneAndUpdate(
      { slug },
      { $setOnInsert: { name, slug } },
      { returnDocument: "after", upsert: true, setDefaultsOnInsert: true }
    );
  } catch (err) {
    if (err?.code === 11000) return Tag.findOne({ slug });
    throw err;
  }
};

/** Recompute usageCount (live articles only) for the tags supplied. */
const refreshTagCounts = async (tagIds = []) => {
  const News = require("../models/News");

  await Promise.all(
    [...new Set(tagIds.map(String))].map(async (id) => {
      const count = await News.countDocuments({ tags: id, deletedAt: null, status: "published" });
      await Tag.findByIdAndUpdate(id, { usageCount: count });
    })
  );
};

/* =========================================================
   CATEGORY
========================================================= */

/** Accepts an ObjectId, a slug or a name. Creates nothing. */
const resolveCategory = async (input) => {
  if (!input) return null;
  const value = String(input).trim();
  if (!value) return null;

  if (/^[0-9a-fA-F]{24}$/.test(value)) {
    const byId = await Category.findById(value).select("_id").lean();
    if (byId) return byId._id;
  }

  const bySlug = await Category.findOne({
    $or: [{ slug: makeSlug(value) }, { name: new RegExp(`^${escapeRegex(value)}$`, "i") }],
  })
    .select("_id")
    .lean();

  return bySlug ? bySlug._id : null;
};

/* =========================================================
   PAYLOAD BUILDER
========================================================= */

const DIRECT_STRING_FIELDS = [
  "title", "subtitle", "shortDescription", "longDescription",
  "language", "country", "region", "destination",
  "sourceName", "sourceUrl", "canonicalUrl",
  "metaTitle", "metaDescription", "focusKeyword", "robots",
  "seoTitle", "seoDescription",
  "externalLink", "adsLink", "imageRedirectUrl",
  "importRowRef",
];

const DIRECT_BOOL_FIELDS = [
  "featured", "trending", "popular", "breakingNews", "editorsPick", "isSponsored",
  "isMainTrending", "isSubTrending", "isCategoryTrending", "isCategorySubTrending",
  "aiGenerated", "autoUpdateEnabled", "seoAutoGenerated",
];

const DIRECT_NUMBER_FIELDS = ["priority", "homeOrder", "readTime"];

const STATUSES = ["draft", "published", "archived", "scheduled", "trash"];

/** `null` clears an image; anything else is normalised (an empty object also clears). */
const imageInput = (value) => (value === null ? undefined : normalizeImage(value));

/**
 * Convert an arbitrary request body (admin form or import row) into a safe,
 * normalised patch for the News model. Only keys present in `body` end up in
 * the patch, so this is safe for partial updates.
 *
 * @param {object} body
 * @param {{ isCreate?: boolean }} opts
 */
const buildNewsPayload = async (body = {}, { isCreate = false } = {}) => {
  const patch = {};
  const warnings = [];

  /* ---------- plain fields ---------- */

  DIRECT_STRING_FIELDS.forEach((key) => {
    if (body[key] !== undefined) patch[key] = String(body[key] ?? "").trim();
  });

  DIRECT_BOOL_FIELDS.forEach((key) => {
    if (body[key] !== undefined) patch[key] = toBool(body[key]);
  });

  DIRECT_NUMBER_FIELDS.forEach((key) => {
    if (body[key] !== undefined) patch[key] = parseNumber(body[key], 0);
  });

  /* ---------- descriptions ---------- */

  if (body.description !== undefined) {
    patch.description = sanitizeInline(String(body.description));
    // Keep the two short-description fields in sync unless both were sent.
    if (body.shortDescription === undefined) patch.shortDescription = patch.description;
  } else if (body.shortDescription !== undefined) {
    patch.description = sanitizeInline(String(body.shortDescription));
  }

  /* ---------- rich content ---------- */

  if (body.content !== undefined) {
    patch.content = sanitizeContent(String(body.content));
    patch.contentText = toPlainText(patch.content);
  }

  if (body.contentBlocks !== undefined) {
    patch.contentBlocks = Array.isArray(body.contentBlocks) ? body.contentBlocks : [];
  }

  if (patch.content !== undefined || patch.contentBlocks !== undefined) {
    patch.readTime =
      body.readTime !== undefined && Number(body.readTime) > 0
        ? parseNumber(body.readTime, 1)
        : calcReadTime(patch.content ?? body.content ?? "", patch.contentBlocks || []);
  }

  if (body.excerpt !== undefined) {
    patch.excerpt = sanitizeInline(String(body.excerpt));
  } else if (isCreate && patch.content) {
    patch.excerpt = makeExcerpt(patch.content);
  }

  /* ---------- taxonomy ---------- */

  if (body.category !== undefined) {
    const catId = await resolveCategory(body.category);
    if (catId) patch.category = catId;
    else warnings.push(`Category not found: ${body.category}`);
  }

  if (body.subCategory !== undefined) {
    if (!body.subCategory) {
      patch.subCategory = null;
    } else {
      const subId = await resolveCategory(body.subCategory);
      if (subId) patch.subCategory = subId;
      else warnings.push(`Sub category not found: ${body.subCategory}`);
    }
  }

  if (body.tags !== undefined) {
    const { ids, names } = await resolveTags(body.tags);
    patch.tags = ids;
    patch.tagNames = names;
  }

  /* ---------- author ---------- */

  if (
    body.author !== undefined ||
    body.authorName !== undefined ||
    body.authorImage !== undefined ||
    body.authorBio !== undefined
  ) {
    const incoming = typeof body.author === "object" && body.author ? body.author : {};

    patch.author = {
      name: (incoming.name ?? body.authorName ?? "").toString().trim(),
      slug: makeSlug(incoming.name ?? body.authorName ?? ""),
      image: normalizeImage(incoming.image ?? body.authorImage),
      bio: sanitizeInline(incoming.bio ?? body.authorBio ?? ""),
      designation: (incoming.designation ?? body.authorDesignation ?? "").toString(),
      email: (incoming.email ?? body.authorEmail ?? "").toString(),
      redirectUrl: (incoming.redirectUrl ?? body.authorRedirectUrl ?? "").toString(),
      social: incoming.social || {},
    };
  }

  /* ---------- images ---------- */

  ["featuredImage", "image", "ogImage", "twitterImage"].forEach((key) => {
    if (body[key] !== undefined) patch[key] = imageInput(body[key]);
  });
  if (body.gallery !== undefined) patch.gallery = normalizeGallery(body.gallery);

  /* ---------- video ---------- */

  if (body.videos !== undefined) {
    const list = Array.isArray(body.videos) ? body.videos : [body.videos];
    patch.videos = list
      .filter((v) => v && (typeof v === "string" ? v : v.url))
      .map((v) =>
        typeof v === "string"
          ? { url: v }
          : {
              url: v.url,
              title: v.title || "",
              caption: v.caption || "",
              redirectUrl: v.redirectUrl || "",
              provider: v.provider || "",
              duration: parseNumber(v.duration, 0) || undefined,
              thumbnail: normalizeImage(v.thumbnail),
            }
      );
  }

  /* ---------- cta / ads ---------- */

  if (body.cta !== undefined) {
    const cta = body.cta || {};
    patch.cta =
      cta.label || cta.url
        ? {
            label: String(cta.label || "").trim(),
            url: String(cta.url || "").trim(),
            style: ["primary", "secondary", "ghost"].includes(cta.style) ? cta.style : "primary",
            openInNewTab: toBool(cta.openInNewTab, true),
          }
        : undefined;
  }

  if (body.advertisement !== undefined) {
    const ad = body.advertisement || {};
    patch.advertisement = {
      code: String(ad.code || ""),
      position: String(ad.position || ""),
      enabled: toBool(ad.enabled, true),
    };
  }

  /* ---------- relations ---------- */

  if (body.relatedNews !== undefined) {
    patch.relatedNews = parseList(body.relatedNews).filter((id) => /^[0-9a-fA-F]{24}$/.test(id));
  }

  if (body.internalLinks !== undefined) {
    patch.internalLinks = Array.isArray(body.internalLinks) ? body.internalLinks : [];
  }

  if (body.affiliateLinks !== undefined) {
    patch.affiliateLinks = Array.isArray(body.affiliateLinks) ? body.affiliateLinks : [];
  }

  if (body.sourceLinks !== undefined) patch.sourceLinks = parseList(body.sourceLinks);
  if (body.seoKeywords !== undefined) patch.seoKeywords = parseList(body.seoKeywords);

  /* ---------- schema.org ---------- */

  // Stored as `schemaMarkup`; `schema` is kept as an input alias.
  const incomingSchema = body.schemaMarkup !== undefined ? body.schemaMarkup : body.schema;

  if (incomingSchema !== undefined) {
    if (typeof incomingSchema === "string") {
      try {
        patch.schemaMarkup = incomingSchema.trim() ? JSON.parse(incomingSchema) : null;
      } catch {
        warnings.push("Schema JSON is invalid and was ignored");
      }
    } else {
      patch.schemaMarkup = incomingSchema;
    }
  }

  /* ---------- publishing ---------- */

  if (body.publishedDate !== undefined) {
    const d = parseDate(body.publishedDate);
    if (d) patch.publishedDate = d;
    else if (body.publishedDate) warnings.push(`Invalid publishedDate: ${body.publishedDate}`);
  }

  if (body.status !== undefined) {
    if (STATUSES.includes(body.status)) patch.status = body.status;
    else warnings.push(`Unknown status "${body.status}" ignored`);
  }

  if (body.scheduledAt !== undefined) {
    const d = parseDate(body.scheduledAt);
    patch.scheduledAt = d;
    // A future publish time always wins: the article waits for it.
    if (d && d.getTime() > Date.now()) patch.status = "scheduled";
  }

  /* ---------- defaults on create ---------- */

  if (isCreate) {
    if (!patch.publishedDate) patch.publishedDate = patch.scheduledAt || new Date();
    if (!patch.language) patch.language = "en";
    if (patch.robots === undefined) patch.robots = "index, follow";
  }

  return { patch, warnings };
};

module.exports = {
  buildNewsPayload,
  resolveTags,
  resolveCategory,
  refreshTagCounts,
};
